import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Environment, Float, PerspectiveCamera, Sparkles, Trail } from '@react-three/drei';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { BokehPass } from 'three/addons/postprocessing/BokehPass.js';
import { SSRPass } from 'three/addons/postprocessing/SSRPass.js';
import { GlitchPass } from 'three/addons/postprocessing/GlitchPass.js';
import { ShaderPass } from 'three/addons/postprocessing/ShaderPass.js';
import { RGBShiftShader } from 'three/addons/shaders/RGBShiftShader.js';
import * as THREE from 'three';
import { motion } from 'framer-motion';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { ArrowDown, ChevronRight, CircleDot, ShieldCheck, X, Activity, Dumbbell, Utensils, Brain, Gauge } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useMMAStore, UserProfile } from '../store/useMMAStore';
import { MagneticButton } from '../components/AppShell';

gsap.registerPlugin(ScrollTrigger);

let scrollProgress = 0;
let pointerX = 0;
let pointerY = 0;
const setScrollProgress = (value: number) => { scrollProgress = THREE.MathUtils.clamp(value, 0, 1); };
const initialForm: UserProfile = { name: '', age: '', experience: 'BEGINNER', goal: 'Build conditioning', trainingDays: '3 DAYS', sessionDuration: '30 MIN', conditioning: 'BUILDING', equipment: 'GLOVES', nutrition: 'NO PREFERENCE', sleep: '7 HOURS' };

function usePointerBus() { useEffect(() => { const move = (event: PointerEvent) => { pointerX = (event.clientX / window.innerWidth) * 2 - 1; pointerY = -(event.clientY / window.innerHeight) * 2 + 1; document.documentElement.style.setProperty('--mx', `${event.clientX}px`); document.documentElement.style.setProperty('--my', `${event.clientY}px`); }; window.addEventListener('pointermove', move, { passive: true }); return () => window.removeEventListener('pointermove', move); }, []); }

function CameraRig() { const { camera } = useThree(); const curve = useMemo(() => new THREE.CatmullRomCurve3([new THREE.Vector3(0, 2.2, 9),new THREE.Vector3(1.8,1.8,6.6),new THREE.Vector3(-2.2,1.5,3.1),new THREE.Vector3(.5,1.15,.9),new THREE.Vector3(2.3,1.8,4.5),new THREE.Vector3(0,2.4,8.2)], false, 'catmullrom', .7), []); useFrame(() => { const point=curve.getPointAt(scrollProgress*.82); camera.position.lerp(point,.055); camera.lookAt(new THREE.Vector3(0,1.05,-.7)); (camera as THREE.PerspectiveCamera).fov=THREE.MathUtils.lerp(47,32,scrollProgress); (camera as THREE.PerspectiveCamera).updateProjectionMatrix(); }); return null; }

function FighterMaterial({ accent=false }: { accent?: boolean }) { return <meshPhysicalMaterial color={accent?'#b9ff39':'#0f1712'} metalness={accent?.78:.58} roughness={accent?.2:.34} clearcoat={.85} clearcoatRoughness={.18} emissive={accent?'#4cff21':'#071008'} emissiveIntensity={accent?1.7:.5}/>; }
function Fighter() { const root=useRef<THREE.Group>(null); const t=useRef(0); useFrame((_,d)=>{t.current+=d;if(!root.current)return;root.current.rotation.y=THREE.MathUtils.lerp(root.current.rotation.y,pointerX*.28+scrollProgress*Math.PI*.7,.04);root.current.rotation.x=THREE.MathUtils.lerp(root.current.rotation.x,pointerY*.09,.04);root.current.position.y=Math.sin(t.current*1.15)*.05+Math.sin(scrollProgress*Math.PI)*.35;root.current.scale.setScalar(THREE.MathUtils.lerp(.9,1.12,scrollProgress));});return <group ref={root} position={[0,-2.15,0]}><Float speed={1.1} rotationIntensity={.08} floatIntensity={.12}><group>
<mesh position={[0,3.85,0]} castShadow><sphereGeometry args={[.5,32,24]}/><FighterMaterial/></mesh><mesh position={[0,3.52,-.44]} scale={[.42,.18,.1]}><sphereGeometry args={[1,24,12]}/><FighterMaterial accent/></mesh><mesh position={[0,2.52,0]} scale={[.96,1.28,.54]} castShadow><capsuleGeometry args={[.8,1.45,12,24]}/><FighterMaterial/></mesh><mesh position={[0,1.63,0]} scale={[.7,.47,.42]}><sphereGeometry args={[1,28,18]}/><FighterMaterial/></mesh>
<mesh position={[-.92,2.72,0]} rotation={[0,0,-.2]} castShadow><capsuleGeometry args={[.18,1.62,10,18]}/><FighterMaterial/></mesh><mesh position={[.92,2.72,0]} rotation={[0,0,.2]} castShadow><capsuleGeometry args={[.18,1.62,10,18]}/><FighterMaterial/></mesh><mesh position={[-1.18,1.83,-.05]} rotation={[0,0,1.25]}><capsuleGeometry args={[.14,1.2,10,18]}/><FighterMaterial/></mesh><mesh position={[1.18,1.83,-.05]} rotation={[0,0,-1.25]}><capsuleGeometry args={[.14,1.2,10,18]}/><FighterMaterial/></mesh><mesh position={[-1.45,1.18,-.08]}><sphereGeometry args={[.27,24,18]}/><FighterMaterial accent/></mesh><mesh position={[1.45,1.18,-.08]}><sphereGeometry args={[.27,24,18]}/><FighterMaterial accent/></mesh><mesh position={[-.44,.25,0]} rotation={[0,0,.055]} castShadow><capsuleGeometry args={[.25,2.15,10,18]}/><FighterMaterial/></mesh><mesh position={[.44,.25,0]} rotation={[0,0,-.055]} castShadow><capsuleGeometry args={[.25,2.15,10,18]}/><FighterMaterial/></mesh><mesh position={[-.6,-1.02,-.08]} rotation={[.08,.06,.05]}><capsuleGeometry args={[.28,1.65,10,18]}/><FighterMaterial/></mesh><mesh position={[.6,-1.02,-.08]} rotation={[.08,-.06,-.05]}><capsuleGeometry args={[.28,1.65,10,18]}/><FighterMaterial/></mesh><mesh position={[-.63,-2.05,-.1]} scale={[1.2,.44,2.3]}><sphereGeometry args={[.46,24,18]}/><FighterMaterial/></mesh><mesh position={[.63,-2.05,-.1]} scale={[1.2,.44,2.3]}><sphereGeometry args={[.46,24,18]}/><FighterMaterial/></mesh></group></Float><pointLight position={[0,2,1.5]} color="#bcff3f" intensity={5} distance={8}/></group>; }

function ParticleField(){const ref=useRef<THREE.Points>(null);const count=18000;const positions=useMemo(()=>{const p=new Float32Array(count*3);for(let i=0;i<count;i++){const r=Math.pow(Math.random(),.45)*15,a=Math.random()*Math.PI*2;p[i*3]=Math.cos(a)*r;p[i*3+1]=(Math.random()-.5)*11;p[i*3+2]=Math.sin(a)*r-2;}return p},[]);const material=useMemo(()=>new THREE.PointsMaterial({color:'#8dff42',size:.022,transparent:true,opacity:.42,depthWrite:false,blending:THREE.AdditiveBlending}),[]);useFrame((state)=>{if(!ref.current)return;ref.current.rotation.y=state.clock.elapsedTime*.012+scrollProgress*.45;ref.current.position.x=THREE.MathUtils.lerp(ref.current.position.x,pointerX*.55,.015);ref.current.position.y=THREE.MathUtils.lerp(ref.current.position.y,-pointerY*.25,.02);material.size=.016+scrollProgress*.022;material.opacity=.26+scrollProgress*.38});const geometry=useMemo(()=>new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(positions,3)),[positions]);return <points ref={ref} geometry={geometry} material={material}/>;}
function Portal(){const ref=useRef<THREE.Group>(null);useFrame((state)=>{if(!ref.current)return;ref.current.rotation.z=state.clock.elapsedTime*.08+scrollProgress*Math.PI*1.3;ref.current.scale.setScalar(1+scrollProgress*.9)});return <group ref={ref} position={[0,1.15,-1.2]} rotation={[Math.PI/2,0,0]}>{[0,1,2].map(i=><mesh key={i} scale={1+i*.25}><torusGeometry args={[1.75,.012+i*.008,12,140]}/><meshBasicMaterial color={i===0?'#caff4b':'#315f2b'} transparent opacity={.62-i*.12} blending={THREE.AdditiveBlending}/></mesh>)}</group>}
function Cityscape(){const blocks=useMemo(()=>Array.from({length:60},(_,i)=>({x:(i%12-5.5)*1.9,z:-8-Math.floor(i/12)*2.2,h:.5+((i*17)%23)/6,r:((i*37)%100)/100})),[]);return <group position={[0,-3,0]}>{blocks.map((b,i)=><mesh key={i} position={[b.x,b.h/2,b.z]} scale={[.9,b.h,.9]}><boxGeometry/><meshStandardMaterial color={b.r>.82?'#18291b':'#0a120c'} emissive="#113014" emissiveIntensity={b.r>.82?.45:.08} metalness={.5} roughness={.72}/></mesh>)}</group>}
function VolumetricBeams(){const group=useRef<THREE.Group>(null);useFrame((state)=>{if(!group.current)return;group.current.rotation.y=Math.sin(state.clock.elapsedTime*.05)*.18+scrollProgress*.7});return <group ref={group} position={[0,1,-2]}>{[-4,-1.7,1.8,4.2].map((x,i)=><mesh key={i} position={[x,2,-3.5]} rotation={[.15,.2,(i-1.5)*.08]}><coneGeometry args={[.75,7,24,1,true]}/><meshBasicMaterial color="#7dff4a" transparent opacity={.035+scrollProgress*.025} depthWrite={false} side={THREE.DoubleSide} blending={THREE.AdditiveBlending}/></mesh>)}</group>}
function LiquidFloor(){return <mesh rotation={[-Math.PI/2,0,0]} position={[0,-3.1,-2]} receiveShadow><planeGeometry args={[34,34,40,40]}/><meshStandardMaterial color="#050a06" metalness={.88} roughness={.16} emissive="#0b1e0c" emissiveIntensity={.09}/></mesh>}
function MorphGrid(){const ref=useRef<THREE.Mesh>(null);const material=useMemo(()=>new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{uTime:{value:0},uScroll:{value:0}},vertexShader:`uniform float uTime; uniform float uScroll; varying float vWave; void main(){vec3 p=position;float w=sin(p.x*1.2+uTime)*.16+cos(p.y*1.5-uTime*.8)*.13;p.z+=w*(.25+uScroll*1.2);vWave=w;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.);}`,fragmentShader:`varying float vWave;void main(){gl_FragColor=vec4(.16,.9,.06,.1+abs(vWave)*.9);}`}),[]);useFrame((state)=>{material.uniforms.uTime.value=state.clock.elapsedTime;material.uniforms.uScroll.value=scrollProgress;if(ref.current)ref.current.rotation.z=scrollProgress*.22});return <mesh ref={ref} position={[0,1,-5]} rotation={[0,0,-.12]} material={material}><planeGeometry args={[18,9,42,24]}/></mesh>}
function PostFX(){const {gl,scene,camera,size}=useThree();const composerRef=useRef<EffectComposer|null>(null);const glitchRef=useRef<GlitchPass|null>(null);const bokehRef=useRef<BokehPass|null>(null);useEffect(()=>{gl.toneMapping=THREE.ACESFilmicToneMapping;gl.toneMappingExposure=1.12;const composer=new EffectComposer(gl);composer.addPass(new RenderPass(scene,camera));const ssr=new SSRPass({renderer:gl,scene,camera,width:Math.max(1,size.width),height:Math.max(1,size.height)});ssr.opacity=.32;ssr.maxDistance=24;ssr.thickness=.02;composer.addPass(ssr);composer.addPass(new UnrealBloomPass(new THREE.Vector2(size.width,size.height),1.4,.65,.18));const bokeh=new BokehPass(scene,camera,{focus:6,aperture:.00018,maxblur:.008});composer.addPass(bokeh);const glitch=new GlitchPass();glitch.enabled=false;composer.addPass(glitch);const rgb=new ShaderPass(RGBShiftShader);rgb.uniforms.amount.value=.0008;composer.addPass(rgb);composer.addPass(new OutputPass());composer.setSize(size.width,size.height);composerRef.current=composer;bokehRef.current=bokeh;glitchRef.current=glitch;return()=>{composer.dispose();composerRef.current=null}},[gl,scene,camera,size.width,size.height]);useFrame((_,delta)=>{if(!composerRef.current)return;const p=scrollProgress;if(bokehRef.current){bokehRef.current.uniforms.focus.value=THREE.MathUtils.lerp(8.5,3.2,p);bokehRef.current.uniforms.aperture.value=THREE.MathUtils.lerp(.00012,.00032,p)}if(glitchRef.current)glitchRef.current.enabled=(p>.42&&p<.55)||(p>.82&&p<.88);composerRef.current.render(delta)},1);return null}
function ArenaScene(){return <><color attach="background" args={['#020503']}/><fog attach="fog" args={['#020503',5,25]}/><ambientLight intensity={.55} color="#6d876c"/><directionalLight position={[4,8,4]} intensity={2.4} color="#caffba" castShadow/><pointLight position={[-5,2,2]} intensity={8} distance={16} color="#3cff2c"/><pointLight position={[6,1,-2]} intensity={7} distance={18} color="#b6ff55"/><CameraRig/><Environment preset="night"/><ParticleField/><Sparkles count={1200} scale={[18,10,18]} size={1.2} speed={.16} color="#a1ff58" opacity={.26}/><Cityscape/><LiquidFloor/><VolumetricBeams/><Portal/><MorphGrid/><Fighter/><PostFX/></>}

function Onboarding({onClose,onSubmit,form,update}:{onClose:()=>void;onSubmit:(e:FormEvent)=>void;form:UserProfile;update:(key:keyof UserProfile,value:string)=>void}){return <motion.div className="onboarding-backdrop" initial={{opacity:0}} animate={{opacity:1}}><motion.form className="onboarding-panel onboarding-3d" onSubmit={onSubmit} initial={{y:70,opacity:0,rotateX:12}} animate={{y:0,opacity:1,rotateX:0}}><button className="onboarding-close" type="button" onClick={onClose}><X size={18}/></button><div className="eyebrow"><span className="eyebrow-line"/> ATHLETE DNA / CALIBRATION</div><h2>Build your<br/><em>roadmap.</em></h2><p className="form-intro">Feed the system a few signals. Forge will build your starting training path, recovery rhythm and nutrition direction.</p><label>CALL SIGN<input autoFocus required value={form.name} onChange={e=>update('name',e.target.value)} placeholder="Your name"/></label><div className="form-grid"><label>EXPERIENCE<select value={form.experience} onChange={e=>update('experience',e.target.value)}><option>BEGINNER</option><option>INTERMEDIATE</option><option>ADVANCED</option></select></label><label>TRAINING DAYS<select value={form.trainingDays} onChange={e=>update('trainingDays',e.target.value)}><option>2 DAYS</option><option>3 DAYS</option><option>4 DAYS</option><option>5 DAYS</option></select></label><label>PRIMARY GOAL<select value={form.goal} onChange={e=>update('goal',e.target.value)}><option>Build conditioning</option><option>Learn MMA</option><option>Improve striking</option><option>Self-defense education</option></select></label><label>SESSION LENGTH<select value={form.sessionDuration} onChange={e=>update('sessionDuration',e.target.value)}><option>20 MIN</option><option>30 MIN</option><option>45 MIN</option><option>60 MIN</option></select></label></div><div className="form-footer"><span><ShieldCheck size={15}/> EDUCATIONAL / ADAPTIVE / SAFE</span><MagneticButton type="submit">GENERATE ROADMAP</MagneticButton></div></motion.form></motion.div>}
function ScrollSection({eyebrow,title,body,index,icon,action,dark=false}:{eyebrow:string;title:string;body:string;index:string;icon:React.ReactNode;action?:string;dark?:boolean}){return <section className={`forge-section ${dark?'forge-section-dark':''}`} data-scroll-section><div className="section-index">{index}</div><div className="section-copy"><div className="eyebrow"><span className="eyebrow-line"/> {eyebrow}</div><h2 className="split-title">{title}</h2><p>{body}</p>{action&&<div className="section-action">{action}<ChevronRight size={15}/></div>}</div><div className="section-icon">{icon}</div></section>}

export default function LandingPage(){const [showOnboarding,setShowOnboarding]=useState(false);const [form,setForm]=useState(initialForm);const [progressLabel,setProgressLabel]=useState('00');const setProfile=useMMAStore(s=>s.setProfile);const navigate=useNavigate();usePointerBus();const update=(key:keyof UserProfile,value:string)=>setForm(c=>({...c,[key]:value}));const submit=(event:FormEvent)=>{event.preventDefault();setProfile(form);setShowOnboarding(false);navigate('/dashboard')};useEffect(()=>{const root=document.querySelector('.landing-page');if(!root)return;const sections=gsap.utils.toArray<HTMLElement>('[data-scroll-section]');const sectionTriggers=sections.map(section=>gsap.fromTo(section.querySelector('.section-copy'),{y:100,opacity:0,clipPath:'inset(20% 0 0 0)'},{y:0,opacity:1,clipPath:'inset(0% 0 0 0)',ease:'none',scrollTrigger:{trigger:section,start:'top 80%',end:'bottom 35%',scrub:1.1}}).scrollTrigger);const master=ScrollTrigger.create({trigger:root,start:'top top',end:'bottom bottom',scrub:true,onUpdate:self=>{setScrollProgress(self.progress);setProgressLabel(String(Math.round(self.progress*100)).padStart(2,'0'));root.style.setProperty('--scroll-progress',self.progress.toFixed(4))}});gsap.to('.hero-title .hero-word',{yPercent:-22,stagger:.08,scrollTrigger:{trigger:root,start:'top top',end:'+=1000',scrub:true}});gsap.to('.hero-sub',{xPercent:16,opacity:.25,scrollTrigger:{trigger:root,start:'top top',end:'+=850',scrub:true}});gsap.to('.hero-ring',{rotate:250,scale:1.5,scrollTrigger:{trigger:root,start:'top top',end:'+=1600',scrub:true}});return()=>{master.kill();sectionTriggers.forEach(t=>t?.kill());ScrollTrigger.getAll().forEach(t=>t.kill())}},[]);return <div className="landing-page forge-landing"><div className="forge-noise"/><div className="forge-grid"/><div className="forge-cursor"><span/></div><div className="forge-progress"><span>SCROLL /</span><strong>{progressLabel}</strong><i/></div><div className="forge-side-rail"><span>FORGE / MMA</span><span>SCROLL TO ADAPT</span></div><div className="forge-canvas-wrap"><Canvas shadows dpr={[1,1.45]} camera={{position:[0,2.2,9],fov:47}} gl={{antialias:true,powerPreference:'high-performance',alpha:false}}><PerspectiveCamera makeDefault position={[0,2.2,9]} fov={47}/><ArenaScene/></Canvas></div><div className="hero-vignette"/>
<section className="forge-hero" data-scroll-section><div className="hero-kicker"><span>01 / ENTRY PROTOCOL</span><span>WEBGL PERFORMANCE SYSTEM / V. 02</span></div><div className="hero-center"><div className="hero-micro">DISCIPLINE → FORM → IMPACT</div><h1 className="hero-title"><span className="hero-word">FORGE</span><span className="hero-word title-offset">YOUR</span><span className="hero-word title-accent">FIGHT<b>.</b></span></h1><p className="hero-sub">A cinematic MMA training system that turns your profile into a living roadmap for movement, conditioning and recovery.</p><div className="hero-cta-row"><MagneticButton onClick={()=>setShowOnboarding(true)}>BUILD MY ROADMAP</MagneticButton><button className="ghost-cta" onClick={()=>navigate('/training')}>ENTER TRAINING<ChevronRight size={16}/></button></div></div><div className="hero-meta"><span><CircleDot size={11}/> LIVE 3D ENGINE</span><span>ADAPTIVE / SAFE / ATHLETE-FIRST</span></div><div className="hero-ring"/><div className="hero-bottom-scroll"><ArrowDown size={16}/> SCROLL THE EXPERIENCE</div></section>
<ScrollSection index="01" eyebrow="THE COMMAND LAYER" title="Your training becomes a system." body="Every session is part of a larger loop. Strength, conditioning, technique, recovery and nutrition are treated as connected signals instead of isolated workouts." icon={<Gauge size={74} strokeWidth={1}/>} action="OPEN COMMAND"/><ScrollSection index="02" eyebrow="TRAINING ENGINE" title="Learn the movement. Repeat with intent." body="Progressive striking, conditioning and movement blocks are surfaced around your current level, available equipment and weekly training rhythm." icon={<Dumbbell size={74} strokeWidth={1}/>} action="START TRAINING" dark/><ScrollSection index="03" eyebrow="ANATOMY LAYER" title="See where the work lands." body="Explore target zones, weak links and training emphasis through an anatomical layer designed to make your preparation more deliberate." icon={<Brain size={74} strokeWidth={1}/>} action="OPEN ANATOMY"/><ScrollSection index="04" eyebrow="FUEL PROTOCOL" title="Performance is built outside the mat." body="Use your roadmap to organize meals, hydration and recovery habits around the workload you actually train, rather than generic fitness advice." icon={<Utensils size={74} strokeWidth={1}/>} action="OPEN FUEL" dark/><ScrollSection index="05" eyebrow="PROGRESS SIGNAL" title="The graph should move because you did." body="Track consistency, completed sessions and training streaks so the app becomes a feedback loop instead of another dashboard you forget to open." icon={<Activity size={74} strokeWidth={1}/>} action="VIEW PROGRESS"/><section className="forge-final" data-scroll-section><div className="final-grid"/><div className="final-copy"><div className="eyebrow"><span className="eyebrow-line"/> FINAL CALIBRATION</div><h2>BUILD THE<br/><em>ROADMAP.</em></h2><p>Give Forge the signals. Start with a plan. Keep adjusting as the athlete changes.</p><MagneticButton onClick={()=>setShowOnboarding(true)}>GENERATE MY ROADMAP</MagneticButton></div><div className="final-readout"><span>OUTPUT</span><strong>00 → 100</strong><i>TRAIN / RECOVER / REPEAT</i></div></section>{showOnboarding&&<Onboarding onClose={()=>setShowOnboarding(false)} onSubmit={submit} form={form} update={update}/>}</div>;
}
