import { useState } from 'react';
import { ArrowUpRight, Droplets, Leaf, Plus, Utensils } from 'lucide-react';
import { motion } from 'framer-motion';
import { meals } from '../data/training';
import { useMMAStore } from '../store/useMMAStore';
import { PageLabel, ProgressBar, Stat } from '../components/AppShell';

export default function NutritionPage() {
  const [active, setActive] = useState<string | null>(null);
  const profile = useMMAStore((state) => state.profile);
  return <div className="page-shell nutrition-page"><div className="page-top-row"><PageLabel eyebrow="FUEL LAB / DAILY RHYTHM" title="Feed the work." detail={`An educational rhythm for ${profile?.name || 'your'} training days.`} /><div className="nutrition-mark"><span>DAY 04</span><strong>TRAIN</strong></div></div><div className="nutrition-top"><section className="fuel-score glass-panel"><div className="panel-topline"><span>FUEL READOUT</span><span>ESTIMATES / NOT PRESCRIPTIONS</span></div><div className="fuel-score-main"><div className="ring ring-large"><strong>82</strong><span>FUEL<br />INDEX</span></div><div><div className="eyebrow">TODAY'S TARGET</div><h2>Steady energy.<br /><em>Clean recovery.</em></h2><p>Use familiar foods, hydrate consistently, and adjust to your own response.</p></div></div><div className="fuel-stats"><Stat value="2.4L" label="HYDRATION" accent /><Stat value="125g" label="PROTEIN / EST." /><Stat value="03:1" label="MEAL RHYTHM" /></div></section><section className="hydration-panel"><Droplets size={22} /><span className="eyebrow">HYDRATION CHECK</span><strong>06 / 08</strong><ProgressBar value={75} valueLabel="6 glasses logged" /><p>One glass now. One after the session.</p></section></div><div className="meal-section"><div className="section-marker"><span>01</span><span>MEAL SEQUENCE</span><span className="line" /></div><div className="meal-list">{meals.map((meal, index) => <motion.article layout key={meal.id} className={`meal-card ${active === meal.id ? 'expanded' : ''}`} onClick={() => setActive(active === meal.id ? null : meal.id)}><div className="meal-visual"><div className={`meal-orb orb-${index}`} /><span>0{index + 1}</span></div><div className="meal-main"><div className="meal-time">{meal.time} <span>{meal.tag}</span></div><h3>{meal.name}</h3><p>{meal.ingredients}</p>{active === meal.id && <motion.div className="meal-expanded" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }}><p>{meal.description}</p><div className="macro-row">{Object.entries(meal.macros).map(([key, value]) => <span key={key}><b>{value}</b> {key.toUpperCase()}</span>)}</div></motion.div>}</div><button className="meal-open" aria-label={`Open ${meal.name}`}>{active === meal.id ? <Plus size={17} className="rotated" /> : <ArrowUpRight size={17} />}</button></motion.article>)}</div></div><div className="nutrition-foot"><span><Leaf size={14} /> YOUR RHYTHM IS A TRAINING TOOL</span><span><Utensils size={14} /> SWAP INGREDIENTS TO FIT YOUR LIFE</span></div></div>;
}
