import { ArrowUpRight, Award, Check, Flame, Target, Trophy } from 'lucide-react';
import { motion } from 'framer-motion';
import { PageLabel, ProgressBar, Stat } from '../components/AppShell';
import { useMMAStore } from '../store/useMMAStore';

const skills = [['TECHNIQUE', 78], ['CONDITIONING', 64], ['MOBILITY', 71], ['REACTION', 53]];
const milestones = [{ name: 'FIRST SESSION', detail: 'You showed up.', done: true, icon: Check }, { name: '3 DAY STREAK', detail: 'Rhythm established.', done: true, icon: Flame }, { name: 'FIRST WEEK', detail: '3 sessions remaining.', done: false, icon: Target }, { name: '10 SESSIONS', detail: 'Long game loading.', done: false, icon: Trophy }];

export default function ProgressPage() {
  const completed = useMMAStore((state) => state.completedWorkouts);
  const streak = useMMAStore((state) => state.trainingStreak);
  return <div className="page-shell progress-page"><div className="page-top-row"><PageLabel eyebrow="PROGRESS / ADAPTATION LOG" title="The work leaves a trace." detail="Every session compounds. Keep the signal honest." /><div className="log-id">LOG / 0142<br /><strong>WEEK 01</strong></div></div><div className="progress-hero"><section className="progress-main glass-panel"><div className="panel-topline"><span>YOUR EVOLUTION</span><span>LAST 07 DAYS</span></div><div className="progress-readout"><div className="ring"><strong>{streak}</strong><span>DAY<br />STREAK</span></div><div><div className="eyebrow">CONSISTENCY SIGNAL</div><h2>Momentum<br /><em>is a skill.</em></h2></div></div><div className="volume-chart">{[32, 44, 38, 65, 54, 78, 90].map((height, index) => <div className="volume-col" key={index}><motion.i initial={{ height: 0 }} animate={{ height: `${height}%` }} transition={{ delay: index * 0.08, duration: 0.8 }} className={index === 6 ? 'active' : ''} /><span>{['M', 'T', 'W', 'T', 'F', 'S', 'S'][index]}</span></div>)}</div></section><section className="progress-stats"><Stat value={completed.length.toString().padStart(2, '0')} label="TOTAL SESSIONS" accent /><Stat value="04.8h" label="TRAINING VOLUME" /><Stat value="+18%" label="CONDITIONING TREND" /><div className="next-milestone"><Award size={17} /><span>NEXT MILESTONE</span><strong>FIRST WEEK COMPLETE <ArrowUpRight size={14} /></strong><ProgressBar value={42} /></div></section></div><div className="skill-grid"><section className="skill-panel glass-panel"><div className="panel-topline"><span>SKILL MATRIX</span><span>LEVEL 04 / TECHNICAL FOUNDATION</span></div>{skills.map(([name, value]) => <div className="skill-row" key={name}><div><span>{name}</span><strong>{value}<small>/100</small></strong></div><ProgressBar value={value as number} /></div>)}</section><section className="milestone-panel"><div className="panel-topline"><span>ACHIEVEMENTS</span><span>02 / 08 UNLOCKED</span></div>{milestones.map(({ name, detail, done, icon: Icon }) => <div className={`milestone ${done ? 'done' : ''}`} key={name}><div className="milestone-icon"><Icon size={16} /></div><div><strong>{name}</strong><span>{detail}</span></div><span className="milestone-state">{done ? 'UNLOCKED' : 'LOCKED'}</span></div>)}</section></div></div>;
}
